name: My first Action
on: [push]

jobs:
  exempel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Print push success
        run: echo "Hello from GitHub Actions!"